@API_HostAddress = https://localhost:7253

GET {{API_HostAddress}}/books/
Accept: application/json
###

GET {{API_HostAddress}}/books/1904b531-53c9-4376-8da8-3122aa436801
Accept: application/json
###

POST {{API_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "2004b531-53c9-4376-8da8-3122aa436801",
  "title": "Modular Monoliths",
  "author": "Gurame",
  "price": "29.99"
}
###

POST {{API_HostAddress}}/books/2004b531-53c9-4376-8da8-3122aa436801/pricehistory
Accept: application/json
Content-Type: application/json

{
  "id": "2004b531-53c9-4376-8da8-3122aa436801",
  "newPrice": "-19.99"
}
###

DELETE {{API_HostAddress}}/books/2004b531-53c9-4376-8da8-3122aa436801
Accept: application/json
###

POST {{API_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "gurame@gurame.net",
  "password": "P@$$w0rd"
}

###

POST {{API_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "gurame@gurame.net",
  "password": "P@$$w0rd"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJndXJhbWVAZ3VyYW1lLm5ldCIsImlhdCI6MTcxMDExMzkyNiwiZXhwIjoxNzEwMTE3NTI2LCJuYmYiOjE3MTAxMTM5MjZ9.bKT3N3LVaFV9peMUor6VSUnqxiUj5tHE5YG_BzoD27E

# Add item to cart
POST {{API_HostAddress}}/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId": "2004b531-53c9-4376-8da8-3122aa436801",
  "quantity": 3
}

###

# List items in cart
GET {{API_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}
